/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.miru.needit;

public final class R {
    public static final class anim {
        public static final int anim_cling_box_bottom=0x7f040000;
        public static final int anim_layout_appicon_controller=0x7f040001;
        public static final int anim_layout_controller=0x7f040002;
        public static final int dock_bottom_enter=0x7f040003;
        public static final int dock_right_enter=0x7f040004;
        public static final int dock_top_enter=0x7f040005;
        public static final int fast_fade_in=0x7f040006;
        public static final int fast_fade_out=0x7f040007;
        public static final int grow_fade_in=0x7f040008;
        public static final int grow_fade_out=0x7f040009;
        public static final int slide_in_right=0x7f04000a;
    }
    public static final class array {
        public static final int mapviewmode=0x7f060000;
        public static final int mapviewmode_alias=0x7f060001;
    }
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int mask=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int target=0x7f010000;
    }
    public static final class bool {
        public static final int transparent_nav=0x7f070000;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f080000;
        public static final int activity_vertical_margin=0x7f080001;
        public static final int app_icon_size=0x7f080002;
    }
    public static final class drawable {
        public static final int actionbar_background=0x7f020000;
        public static final int bg_speech=0x7f020001;
        public static final int bt_panorama_highlight=0x7f020002;
        public static final int bt_panorama_normal=0x7f020003;
        public static final int bt_panorama_pressed=0x7f020004;
        public static final int btn_green_highlight=0x7f020005;
        public static final int btn_green_normal=0x7f020006;
        public static final int btn_green_pressed=0x7f020007;
        public static final int btn_location_menu_bg=0x7f020008;
        public static final int btn_location_menu_bg_normal=0x7f020009;
        public static final int btn_location_menu_bg_pressed=0x7f02000a;
        public static final int daylight=0x7f02000b;
        public static final int dialog_background=0x7f02000c;
        public static final int ic_action_microphone=0x7f02000d;
        public static final int ic_action_microphone_light=0x7f02000e;
        public static final int ic_action_microphone_light_normal=0x7f02000f;
        public static final int ic_action_microphone_light_pressed=0x7f020010;
        public static final int ic_action_microphone_normal=0x7f020011;
        public static final int ic_action_microphone_pressed=0x7f020012;
        public static final int ic_action_openweb=0x7f020013;
        public static final int ic_action_openweb_light=0x7f020014;
        public static final int ic_action_openweb_light_normal=0x7f020015;
        public static final int ic_action_openweb_light_pressed=0x7f020016;
        public static final int ic_action_openweb_normal=0x7f020017;
        public static final int ic_action_openweb_pressed=0x7f020018;
        public static final int ic_action_search=0x7f020019;
        public static final int ic_angle=0x7f02001a;
        public static final int ic_exit=0x7f02001b;
        public static final int ic_float=0x7f02001c;
        public static final int ic_float_pressed=0x7f02001d;
        public static final int ic_hide=0x7f02001e;
        public static final int ic_launcher=0x7f02001f;
        public static final int ic_location=0x7f020020;
        public static final int ic_map_arrive=0x7f020021;
        public static final int ic_map_arrive_over=0x7f020022;
        public static final int ic_map_no_01=0x7f020023;
        public static final int ic_map_no_02=0x7f020024;
        public static final int ic_map_start=0x7f020025;
        public static final int ic_map_start_over=0x7f020026;
        public static final int ic_mylocation_off=0x7f020027;
        public static final int ic_mylocation_on=0x7f020028;
        public static final int ic_notification=0x7f020029;
        public static final int ic_pin_01=0x7f02002a;
        public static final int ic_pin_02=0x7f02002b;
        public static final int ic_search=0x7f02002c;
        public static final int ic_settings=0x7f02002d;
        public static final int icon=0x7f02002e;
        public static final int menu_bg_pressed=0x7f02002f;
        public static final int pin_ballon_arrow=0x7f020030;
        public static final int pin_ballon_bg=0x7f020031;
        public static final int pin_ballon_on_arrow=0x7f020032;
        public static final int pref_mapsettings=0x7f020033;
        public static final int pref_tabsettings=0x7f020034;
        public static final int pubtrans_ic_mylocation_off=0x7f020035;
        public static final int pubtrans_ic_mylocation_on=0x7f020036;
        public static final int spot_mask=0x7f020037;
        public static final int tab_daum=0x7f020038;
        public static final int tab_daum_normal=0x7f020039;
        public static final int tab_daum_pressed=0x7f02003a;
        public static final int tab_daum_selected=0x7f02003b;
        public static final int tab_google=0x7f02003c;
        public static final int tab_google_normal=0x7f02003d;
        public static final int tab_google_pressed=0x7f02003e;
        public static final int tab_google_selected=0x7f02003f;
        public static final int tab_local=0x7f020040;
        public static final int tab_local_normal=0x7f020041;
        public static final int tab_local_pressed=0x7f020042;
        public static final int tab_local_selected=0x7f020043;
        public static final int tab_naver=0x7f020044;
        public static final int tab_naver_normal=0x7f020045;
        public static final int tab_naver_pressed=0x7f020046;
        public static final int tab_naver_selected=0x7f020047;
        public static final int tab_wikipedia=0x7f020048;
        public static final int tab_wikipedia_normal=0x7f020049;
        public static final int tab_wikipedia_pressed=0x7f02004a;
        public static final int tab_wikipedia_selected=0x7f02004b;
        public static final int tab_youtube=0x7f02004c;
        public static final int tab_youtube_normal=0x7f02004d;
        public static final int tab_youtube_pressed=0x7f02004e;
        public static final int tab_youtube_selected=0x7f02004f;
        public static final int transparent_button_background=0x7f020050;
    }
    public static final class id {
        public static final int FrameLayout1=0x7f0c0008;
        public static final int LinearLayout1=0x7f0c0000;
        public static final int action_settings=0x7f0c0036;
        public static final int all_apps=0x7f0c000d;
        public static final int app_icon=0x7f0c0002;
        public static final int app_menu=0x7f0c000c;
        public static final int btn_exit=0x7f0c0005;
        public static final int btn_hide=0x7f0c0006;
        public static final int btn_settings=0x7f0c0004;
        public static final int button1=0x7f0c000a;
        public static final int content=0x7f0c0009;
        public static final int daum=0x7f0c0024;
        public static final int floating_button=0x7f0c0035;
        public static final int google=0x7f0c001c;
        public static final int hideMapView=0x7f0c0013;
        public static final int horizontalScrollView1=0x7f0c0015;
        public static final int imageView1=0x7f0c000f;
        public static final int label=0x7f0c000b;
        public static final int layout1=0x7f0c0007;
        public static final int layout_icon=0x7f0c0001;
        public static final int layout_menu=0x7f0c0003;
        public static final int local=0x7f0c0030;
        public static final int mapView=0x7f0c000e;
        public static final int menu_location=0x7f0c0011;
        public static final int myLocation=0x7f0c0010;
        public static final int naver=0x7f0c0020;
        public static final int openweb_daum=0x7f0c0026;
        public static final int openweb_google=0x7f0c001e;
        public static final int openweb_naver=0x7f0c0022;
        public static final int openweb_wikipedia=0x7f0c002e;
        public static final int openweb_youtube=0x7f0c002a;
        public static final int searchNearby=0x7f0c0014;
        public static final int search_daum=0x7f0c0025;
        public static final int search_google=0x7f0c001d;
        public static final int search_local=0x7f0c0031;
        public static final int search_naver=0x7f0c0021;
        public static final int search_wikipedia=0x7f0c002d;
        public static final int search_youtube=0x7f0c0029;
        public static final int showMapView=0x7f0c0012;
        public static final int tab_daum=0x7f0c0018;
        public static final int tab_google=0x7f0c0016;
        public static final int tab_local=0x7f0c001b;
        public static final int tab_naver=0x7f0c0017;
        public static final int tab_wikipedia=0x7f0c001a;
        public static final int tab_youtube=0x7f0c0019;
        public static final int voicesearch_daum=0x7f0c0027;
        public static final int voicesearch_google=0x7f0c001f;
        public static final int voicesearch_local=0x7f0c0032;
        public static final int voicesearch_naver=0x7f0c0023;
        public static final int voicesearch_wikipedia=0x7f0c002f;
        public static final int voicesearch_youtube=0x7f0c002b;
        public static final int webview_divider=0x7f0c0034;
        public static final int webview_searchResult=0x7f0c0033;
        public static final int wikipedia=0x7f0c002c;
        public static final int youtube=0x7f0c0028;
    }
    public static final class layout {
        public static final int activity_dialog=0x7f030000;
        public static final int activity_main=0x7f030001;
        public static final int activity_my_location=0x7f030002;
        public static final int application=0x7f030003;
        public static final int dialog_appmenu=0x7f030004;
        public static final int dialog_location=0x7f030005;
        public static final int dialog_searchframe=0x7f030006;
        public static final int layout_floating=0x7f030007;
    }
    public static final class menu {
        public static final int dialog=0x7f0b0000;
        public static final int main=0x7f0b0001;
        public static final int my_location=0x7f0b0002;
    }
    public static final class string {
        public static final int action_settings=0x7f090001;
        public static final int app_name=0x7f090000;
        public static final int cancel=0x7f090015;
        public static final int daum=0x7f090006;
        public static final int enablegps=0x7f090010;
        public static final int exit=0x7f090014;
        public static final int exit_app=0x7f090013;
        public static final int google=0x7f090004;
        public static final int gpsdisabled=0x7f09000f;
        public static final int hello_world=0x7f090002;
        public static final int hide_map=0x7f09000b;
        public static final int loading_location=0x7f09000e;
        public static final int local=0x7f090009;
        public static final int mapview_hybrid=0x7f090027;
        public static final int mapview_vector=0x7f090026;
        public static final int naver=0x7f090005;
        public static final int nothanks=0x7f090011;
        public static final int pref_boot=0x7f090023;
        public static final int pref_boot_desc=0x7f090024;
        public static final int pref_hide_zoom=0x7f090021;
        public static final int pref_hide_zoom_desc=0x7f090022;
        public static final int pref_mapsettings=0x7f090018;
        public static final int pref_mapview_mode=0x7f090025;
        public static final int pref_searchsettings=0x7f090020;
        /**  Preference 
 Preference 
         */
        public static final int pref_settings=0x7f090016;
        public static final int pref_show_daum=0x7f09001c;
        public static final int pref_show_google=0x7f090019;
        public static final int pref_show_google_desc=0x7f09001a;
        public static final int pref_show_local=0x7f09001f;
        public static final int pref_show_naver=0x7f09001b;
        public static final int pref_show_wikipedia=0x7f09001e;
        public static final int pref_show_youtube=0x7f09001d;
        public static final int pref_tabsettings=0x7f090017;
        public static final int search_nearby=0x7f09000c;
        public static final int service_notification=0x7f090012;
        public static final int show_map=0x7f09000a;
        public static final int title_activity_dialog=0x7f090003;
        public static final int voice_search=0x7f09000d;
        public static final int wikipedia=0x7f090008;
        public static final int youtube=0x7f090007;
    }
    public static final class style {
        public static final int ActionBar=0x7f0a0005;
        public static final int ActionBarTitle=0x7f0a0006;
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
         */
        public static final int AppBaseTheme=0x7f0a0000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f0a0001;
        public static final int DialogTheme=0x7f0a0002;
        public static final int NeedIt_Preference=0x7f0a0004;
        public static final int NeedIt_Preference_Dialog=0x7f0a0003;
    }
    public static final class xml {
        public static final int pref_general=0x7f050000;
        public static final int pref_mapsettings=0x7f050001;
        public static final int pref_tabsettings=0x7f050002;
    }
    public static final class styleable {
        /** Attributes that can be used with a SpotlightView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #SpotlightView_mask com.miru.needit:mask}</code></td><td></td></tr>
           <tr><td><code>{@link #SpotlightView_target com.miru.needit:target}</code></td><td></td></tr>
           </table>
           @see #SpotlightView_mask
           @see #SpotlightView_target
         */
        public static final int[] SpotlightView = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.miru.needit.R.attr#mask}
          attribute's value can be found in the {@link #SpotlightView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.miru.needit:mask
        */
        public static final int SpotlightView_mask = 1;
        /**
          <p>This symbol is the offset where the {@link com.miru.needit.R.attr#target}
          attribute's value can be found in the {@link #SpotlightView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.miru.needit:target
        */
        public static final int SpotlightView_target = 0;
    };
}
